name: Java CI with Gradle

# master 브랜치의 push와 pull로 CI가 작동
on:
  push:
    branches: [ "be-dev" ]
  pull_request:
    branches: [ "be-dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          # 자신이 사용하는 자바 버전에 맞춰주자
          java-version: '11'
          distribution: 'temurin'
      - uses : actions/checkout@v3
      #1
      # 해당 부분은 상당히 중요함 (글에서 부가설명)
      # application.yml는 외부에 노출되면 안되므로 Actions가 빌드될때마다 해당 Repository의 Secret 설정을
      # 이용하여서 설정 파일을 생성해줌 (github에 commit 되는게 아님!)
      - run : touch ./server/src/main/resources/application.yml
      - run : echo "${{ secrets.APPLICATION }}" > ./server/src/main/resources/application.yml
      - run : cat ./server/src/main/resources/application.yml

      # gradlew에 권한 부여
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./server/gradlew
        shell: bash

      # gradlew 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      # 빌드를 성공하면 해당 프로젝트를 zip로 만듬
      # 이름은 run 에서 설정 가능
      - name: Make zip file
        run: zip -r ./main13.zip .
        shell: bash

      #2
      # AWS 계정 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # 깃허브 Secret에 넣어둔 Access key
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # 깃허브 Secret에 넣어둔 Secret key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # 깃허브 Secret에 넣어둔 Region
          aws-region: ${{ secrets.AWS_REGION }}

      #3
      # 만들어 놓은 S3에 해당 zip 파일 저장
      - name: Upload to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./main13.zip s3://api.hard-coding.com/main13.zip

      #4
      # AWS CodeDeploy에 배포
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name seb43_main_013 \
          --deployment-group-name back-L-End \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=api.hard-coding.com,bundleType=zip,key=project/main13.zip \
          --region ${{ secrets.AWS_REGION }}
